version: "3.3"

volumes:
  dbdata:
  esdata:

services:

  web:
    restart: always
    build:
      context: .
      dockerfile: ./compose/web/Dockerfile
    expose:
      - "8000"
    links:
      - db:db
    env_file:
      - ./example.env
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: /start.sh

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./compose/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql
    env_file:
      - ./example.env
    expose:
      - "5432"

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./backend:/app
      - ./compose/nginx:/etc/nginx/conf.d/
    links:
      - web:web

  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    expose:
      - "9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
