version: '3.3'

services:
  test:
    build:
      context: .
      dockerfile: ./compose/web/Dockerfile
    expose:
      - "8000"
    links:
      - db:db
    env_file:
      - ./example.env
    environment:
      - DJANGO_SETTINGS_MODULE=phonebook.settings.test
    volumes:
      - ./backend:/app
      - ./compose/web/runtest.sh:/runtest.sh
    depends_on:
      - db
    command: /runtest.sh