version: "3.3"

services:

  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - db:db
    env_file:
      - ./secrets/django.env
      - ./secrets/db.env
    volumes:
      - ./web/backend:/unmade/phonebook/web/backend
    depends_on:
      - db
    entrypoint: /unmade/phonebook/web/backend/entrypoint.sh

  testweb:
    build: ./web
    links:
      - db:db
    env_file:
      - ./secrets/django.env
      - ./secrets/db.env
    volumes:
      - ./web/backend:/unmade/phonebook/web/backend
    depends_on:
      - db
    entrypoint:
      - /unmade/phonebook/web/backend/test.sh

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql
    env_file:
      - ./secrets/db.env
    expose:
      - "5432"

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./backend:/unmade/phonebook/web/backend
      - ./nginx:/etc/nginx/conf.d/
    links:
      - web:web

volumes:
  dbdata: