version: "3.3"

services:

  web:
    restart: always
    build: ./web/backend
    expose:
      - "8000"
    links:
      - db:db
    env_file:
      - ./secrets/django.env
      - ./secrets/db.env
    volumes:
      - ./web:/home/phonebook/web
    depends_on:
      - db
    entrypoint: /home/phonebook/web/entrypoint.sh

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql
    env_file:
      - ./secrets/db.env
    expose:
      - "5432"

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./backend:/home/phonebook/backend
      - ./nginx:/etc/nginx/conf.d/
    links:
      - backend:backend

volumes:
  dbdata: