# Generated by Django 2.0 on 2017-12-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20160104_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-created_at',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('DF', 'Не требует решения'), ('PR', 'В процессе'), ('NW', 'Новое'), ('SL', 'Решено'), ('RJ', 'Не решено')], default='NW', max_length=2, verbose_name='Статус'),
        ),
    ]
