# Generated by Django 2.0 on 2017-12-08 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20160102_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['email'], 'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['number'], 'verbose_name': 'Phone', 'verbose_name_plural': 'Phones'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='email',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='email',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Additional info'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Additional info'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Number'),
        ),
    ]
