# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50, verbose_name='Отправитель')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('SLVD', 'Решено'), (('RJCT',), 'Не решено'), ('DFLT', 'Не требует решения')], max_length=2, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
                'verbose_name': 'Отзыв',
            },
        ),
    ]
