# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 10:29
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_head', to='employees.Employee'),
        ),
        migrations.AddField(
            model_name='division',
            name='phones',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.Phone'),
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.CompanyCategory'),
        ),
        migrations.AddField(
            model_name='company',
            name='ceo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_ceo', to='employees.Employee'),
        ),
        migrations.AddField(
            model_name='company',
            name='emails',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='phones',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.Phone'),
        ),
        migrations.AddField(
            model_name='center',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='center',
            name='emails',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.Email'),
        ),
        migrations.AddField(
            model_name='center',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center_head', to='employees.Employee'),
        ),
        migrations.AddField(
            model_name='center',
            name='phones',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.Phone'),
        ),
    ]
