# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20160102_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Доп. инф.'),
        ),
    ]
