# Generated by Django 2.0 on 2017-12-08 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_division_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'ordering': ['number', 'name'], 'verbose_name': 'Center', 'verbose_name_plural': 'Centers'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companycategory',
            options={'ordering': ['category'], 'verbose_name': 'Business entity', 'verbose_name_plural': 'Business entities'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['number', 'name'], 'verbose_name': 'Division', 'verbose_name_plural': 'Divisions'},
        ),
        migrations.AlterField(
            model_name='center',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Additional info'),
        ),
        migrations.AlterField(
            model_name='center',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='center',
            name='emails',
            field=models.ManyToManyField(blank=True, to='contacts.Email', verbose_name='Emails'),
        ),
        migrations.AlterField(
            model_name='center',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='center_head', to='employees.Employee', verbose_name='Head'),
        ),
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='center',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='center',
            name='phones',
            field=models.ManyToManyField(blank=True, to='contacts.Phone', verbose_name='Phones'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=400, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.CompanyCategory', verbose_name='Business entity'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ceo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_ceo', to='employees.Employee', verbose_name='CEO'),
        ),
        migrations.AlterField(
            model_name='company',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Additional info'),
        ),
        migrations.AlterField(
            model_name='company',
            name='emails',
            field=models.ManyToManyField(blank=True, to='contacts.Email', verbose_name='Emails'),
        ),
        migrations.AlterField(
            model_name='company',
            name='full_name',
            field=models.TextField(blank=True, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='logos/no-logo.png', upload_to='logos', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phones',
            field=models.ManyToManyField(blank=True, to='contacts.Phone', verbose_name='Phones'),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='companycategory',
            name='category',
            field=models.CharField(max_length=50, unique=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='companycategory',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='division',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Center', verbose_name='Center'),
        ),
        migrations.AlterField(
            model_name='division',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Additional info'),
        ),
        migrations.AlterField(
            model_name='division',
            name='emails',
            field=models.ManyToManyField(blank=True, to='contacts.Email', verbose_name='Emails'),
        ),
        migrations.AlterField(
            model_name='division',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_head', to='employees.Employee', verbose_name='Head'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='division',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='division',
            name='phones',
            field=models.ManyToManyField(blank=True, to='contacts.Phone', verbose_name='Phones'),
        ),
    ]
