# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='firstname',
            options={'verbose_name': 'Имя', 'verbose_name_plural': 'Имена'},
        ),
        migrations.AlterModelOptions(
            name='patronymic',
            options={'verbose_name': 'Отчество', 'verbose_name_plural': 'Отчества'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='surname',
            options={'verbose_name': 'Фамилия', 'verbose_name_plural': 'Фамилии'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='firstname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.FirstName', verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to='employees.Employee', verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Center', verbose_name='Центр'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Доп. инф.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company', verbose_name='Предприятие'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Division', verbose_name='Отделение/Отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emails',
            field=models.ManyToManyField(blank=True, to='contacts.Email', verbose_name='Эл. адреса'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patronymic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Patronymic', verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phones',
            field=models.ManyToManyField(blank=True, to='contacts.Phone', verbose_name='Телефоны'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Surname', verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='firstname',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='patronymic',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='surname',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Фамилия'),
        ),
    ]
