# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20151229_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['surname', 'firstname', 'patronymic'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='firstname',
            options={'ordering': ['name'], 'verbose_name': 'Имя', 'verbose_name_plural': 'Имена'},
        ),
        migrations.AlterModelOptions(
            name='patronymic',
            options={'ordering': ['name'], 'verbose_name': 'Отчество', 'verbose_name_plural': 'Отчества'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='surname',
            options={'ordering': ['name'], 'verbose_name': 'Фамилия', 'verbose_name_plural': 'Фамилии'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary', to='employees.Employee', verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
