# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20160102_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_retired',
            field=models.BooleanField(default=False, verbose_name='Числится уволеным'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary', to='employees.Employee', verbose_name='Является секретарем у'),
        ),
    ]
