# Generated by Django 2.0 on 2017-12-08 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20160226_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['surname', 'firstname', 'patronymic'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='firstname',
            options={'ordering': ['name'], 'verbose_name': 'First name', 'verbose_name_plural': 'First names'},
        ),
        migrations.AlterModelOptions(
            name='patronymic',
            options={'ordering': ['name'], 'verbose_name': 'Patronymic', 'verbose_name_plural': 'Patronymics'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name'], 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterModelOptions(
            name='surname',
            options={'ordering': ['name'], 'verbose_name': 'Surname', 'verbose_name_plural': 'Surnames'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary', to='employees.Employee', verbose_name='Boss'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Center', verbose_name='Center'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Additional info'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Division', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emails',
            field=models.ManyToManyField(blank=True, to='contacts.Email', verbose_name='Emails'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.FirstName', verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_retired',
            field=models.BooleanField(default=False, verbose_name='Is retired'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patronymic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Patronymic', verbose_name='Patronymic'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phones',
            field=models.ManyToManyField(blank=True, to='contacts.Phone', verbose_name='Phones'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Position', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Surname', verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='firstname',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='patronymic',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Patronymic'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='surname',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Surname'),
        ),
    ]
